### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by its-charan-here** [herobd/Visual-Template-Free-Form-Parsing#7]
After executing 
`python eval.py -c saved/detector/checkpoint-iteration150000.pth -n 0 -T -a data_loader=special_dataset=simple`
I am facing Recursion Error, the output looks like this on the console. 
`
loaded iteration 125000
added config[data_loader][special_dataset]=simple
Traceback (most recent call last):
  File "eval.py", line 376, in <module>
    main(args.checkpoint, args.savedir, args.number, index, gpu=args.gpu, shuffle=args.shuffle, setBatch=args.batchsize, config=args.config, thresh=args.thresh, addToConfig=addtoconfig,test=args.test,verbose=args.verbosity)
  File "eval.py", line 117, in main
    model = eval(config['arch'])(config['model'])
  File "/content/drive/My Drive/Yolo Vision template/Visual-Template-Free-Form-Parsing/model/pairing_graph.py", line 49, in __init__
    self.detector = eval(checkpoint['config']['arch'])(detector_config)
  File "/content/drive/My Drive/Yolo Vision template/Visual-Template-Free-Form-Parsing/model/pairing_graph.py", line 49, in __init__
    self.detector = eval(checkpoint['config']['arch'])(detector_config)
  File "/content/drive/My Drive/Yolo Vision template/Visual-Template-Free-Form-Parsing/model/pairing_graph.py", line 49, in __init__
    self.detector = eval(checkpoint['config']['arch'])(detector_config)
  [Previous line repeated 242 more times]
  File "/content/drive/My Drive/Yolo Vision template/Visual-Template-Free-Form-Parsing/model/pairing_graph.py", line 46, in __init__
    checkpoint = torch.load(config['detector_checkpoint'])
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 749, in _legacy_load
    return legacy_load(f)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 671, in legacy_load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "/usr/lib/python3.6/tarfile.py", line 1591, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python3.6/tarfile.py", line 1621, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.6/tarfile.py", line 1445, in __init__
    self.name = os.path.abspath(name) if name else None
  File "/usr/lib/python3.6/posixpath.py", line 379, in abspath
    if not isabs(path):
  File "/usr/lib/python3.6/posixpath.py", line 67, in isabs
    sep = _get_sep(s)
RecursionError: maximum recursion depth exceeded
`

What changes are required to be done ?

**Comment by herobd** [comment]
Is this the pretrained detector, or your own?

**Comment by its-charan-here** [comment]
it's a pretrained detector

**Comment by herobd** [comment]
Whoops. The detector snapshot is actual another snapshot of the pairing model. I'll fix that.

**Comment by herobd** [comment]
Ok, re-download the weights. It has the correct snapshot now.
