### ISSUE TITLE
Errors while running setup.py

### ISSUE THREAD

**Issue by PyroGenesis** [herobd/Visual-Template-Free-Form-Parsing#8]
Hi,

I am trying to build and run this model on a Windows system. However, I run into errors on executing `python setup.py build develop`
It seems like errors occur during CUDA compilation

Could you help me out with this if possible?

### Versions
Anaconda: 4.9.2
Python: 3.8.5
Pytorch: 1.7.1
CUDA: 11.0.221

### Log
```
Using CUDA
running build
running build_py
creating build
creating build\lib.win-amd64-3.8
creating build\lib.win-amd64-3.8\base
copying base\base_data_loader.py -> build\lib.win-amd64-3.8\base
copying base\base_model.py -> build\lib.win-amd64-3.8\base
copying base\base_trainer.py -> build\lib.win-amd64-3.8\base
copying base\__init__.py -> build\lib.win-amd64-3.8\base
creating build\lib.win-amd64-3.8\data_loader
copying data_loader\data_loaders.py -> build\lib.win-amd64-3.8\data_loader
copying data_loader\__init__.py -> build\lib.win-amd64-3.8\data_loader
creating build\lib.win-amd64-3.8\evaluators
copying evaluators\formsboxdetect_printer.py -> build\lib.win-amd64-3.8\evaluators
copying evaluators\formsfeaturepair_printer.py -> build\lib.win-amd64-3.8\evaluators
copying evaluators\formsgraphpair_printer.py -> build\lib.win-amd64-3.8\evaluators
copying evaluators\__init__.py -> build\lib.win-amd64-3.8\evaluators
creating build\lib.win-amd64-3.8\logger
copying logger\logger.py -> build\lib.win-amd64-3.8\logger
copying logger\__init__.py -> build\lib.win-amd64-3.8\logger
creating build\lib.win-amd64-3.8\model
copying model\alignment_loss.py -> build\lib.win-amd64-3.8\model
copying model\binary_pair_net.py -> build\lib.win-amd64-3.8\model
copying model\binary_pair_real.py -> build\lib.win-amd64-3.8\model
copying model\coordconv.py -> build\lib.win-amd64-3.8\model
copying model\loss.py -> build\lib.win-amd64-3.8\model
copying model\metric.py -> build\lib.win-amd64-3.8\model
copying model\model.py -> build\lib.win-amd64-3.8\model
copying model\net_builder.py -> build\lib.win-amd64-3.8\model
copying model\optimize.py -> build\lib.win-amd64-3.8\model
copying model\pairing_graph.py -> build\lib.win-amd64-3.8\model
copying model\roi_align.py -> build\lib.win-amd64-3.8\model
copying model\simpleNN.py -> build\lib.win-amd64-3.8\model
copying model\vgg.py -> build\lib.win-amd64-3.8\model
copying model\yolo_box_detector.py -> build\lib.win-amd64-3.8\model
copying model\yolo_loss.py -> build\lib.win-amd64-3.8\model
copying model\__init__.py -> build\lib.win-amd64-3.8\model
creating build\lib.win-amd64-3.8\trainer
copying trainer\box_detect_trainer.py -> build\lib.win-amd64-3.8\trainer
copying trainer\feature_pair_trainer.py -> build\lib.win-amd64-3.8\trainer
copying trainer\graph_pair_trainer.py -> build\lib.win-amd64-3.8\trainer
copying trainer\trainer.py -> build\lib.win-amd64-3.8\trainer
copying trainer\__init__.py -> build\lib.win-amd64-3.8\trainer
creating build\lib.win-amd64-3.8\utils
copying utils\add_size_to_annotations.py -> build\lib.win-amd64-3.8\utils
copying utils\augmentation.py -> build\lib.win-amd64-3.8\utils
copying utils\crop_transform.py -> build\lib.win-amd64-3.8\utils
copying utils\fast_inverse.py -> build\lib.win-amd64-3.8\utils
copying utils\forms_annotations.py -> build\lib.win-amd64-3.8\utils
copying utils\string_utils.py -> build\lib.win-amd64-3.8\utils
copying utils\transformation_utils.py -> build\lib.win-amd64-3.8\utils
copying utils\util.py -> build\lib.win-amd64-3.8\utils
copying utils\yolo_tools.py -> build\lib.win-amd64-3.8\utils
copying utils\__init__.py -> build\lib.win-amd64-3.8\utils
creating build\lib.win-amd64-3.8\model\modules
copying model\modules\__init__.py -> build\lib.win-amd64-3.8\model\modules
running build_ext
D:\ProgramFiles\anaconda3\lib\site-packages\torch\utils\cpp_extension.py:287: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'model._C' extension
creating D:\Extraction\Visual_Template_Free_Form_Parsing\repo\build\temp.win-amd64-3.8
creating D:\Extraction\Visual_Template_Free_Form_Parsing\repo\build\temp.win-amd64-3.8\Release
creating D:\Extraction\Visual_Template_Free_Form_Parsing\repo\build\temp.win-amd64-3.8\Release\Extraction
creating D:\Extraction\Visual_Template_Free_Form_Parsing\repo\build\temp.win-amd64-3.8\Release\Extraction\Visual_Template_Free_Form_Parsing
creating D:\Extraction\Visual_Template_Free_Form_Parsing\repo\build\temp.win-amd64-3.8\Release\Extraction\Visual_Template_Free_Form_Parsing\repo
creating D:\Extraction\Visual_Template_Free_Form_Parsing\repo\build\temp.win-amd64-3.8\Release\Extraction\Visual_Template_Free_Form_Parsing\repo\model
creating D:\Extraction\Visual_Template_Free_Form_Parsing\repo\build\temp.win-amd64-3.8\Release\Extraction\Visual_Template_Free_Form_Parsing\repo\model\csrc
creating D:\Extraction\Visual_Template_Free_Form_Parsing\repo\build\temp.win-amd64-3.8\Release\Extraction\Visual_Template_Free_Form_Parsing\repo\model\csrc\cpu
creating D:\Extraction\Visual_Template_Free_Form_Parsing\repo\build\temp.win-amd64-3.8\Release\Extraction\Visual_Template_Free_Form_Parsing\repo\model\csrc\cuda
Emitting ninja build file D:\Extraction\Visual_Template_Free_Form_Parsing\repo\build\temp.win-amd64-3.8\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin\nvcc --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA -ID:\Extraction\Visual_Template_Free_Form_Parsing\repo\model\csrc -ID:\ProgramFiles\anaconda3\lib\site-packages\torch\include -ID:\ProgramFiles\anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -ID:\ProgramFiles\anaconda3\lib\site-packages\torch\include\TH -ID:\ProgramFiles\anaconda3\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include" -ID:\ProgramFiles\anaconda3\include -ID:\ProgramFiles\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" -c D:\Extraction\Visual_Template_Free_Form_Parsing\repo\model\csrc\cuda\ROIAlign_cuda.cu -o D:\Extraction\Visual_Template_Free_Form_Parsing\repo\build\temp.win-amd64-3.8\Release\Extraction\Visual_Template_Free_Form_Parsing\repo\model\csrc\cuda\ROIAlign_cuda.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75
FAILED: D:/Extraction/Visual_Template_Free_Form_Parsing/repo/build/temp.win-amd64-3.8/Release/Extraction/Visual_Template_Free_Form_Parsing/repo/model/csrc/cuda/ROIAlign_cuda.obj
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin\nvcc --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA -ID:\Extraction\Visual_Template_Free_Form_Parsing\repo\model\csrc -ID:\ProgramFiles\anaconda3\lib\site-packages\torch\include -ID:\ProgramFiles\anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -ID:\ProgramFiles\anaconda3\lib\site-packages\torch\include\TH -ID:\ProgramFiles\anaconda3\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include" -ID:\ProgramFiles\anaconda3\include -ID:\ProgramFiles\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" -c D:\Extraction\Visual_Template_Free_Form_Parsing\repo\model\csrc\cuda\ROIAlign_cuda.cu -o D:\Extraction\Visual_Template_Free_Form_Parsing\repo\build\temp.win-amd64-3.8\Release\Extraction\Visual_Template_Free_Form_Parsing\repo\model\csrc\cuda\ROIAlign_cuda.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75
D:/Extraction/Visual_Template_Free_Form_Parsing/repo/model/csrc/cuda/ROIAlign_cuda.cu(275): error: no instance of function template "THCCeilDiv" matches the argument list
            argument types are: (long long, long)

D:/Extraction/Visual_Template_Free_Form_Parsing/repo/model/csrc/cuda/ROIAlign_cuda.cu(275): error: no instance of overloaded function "std::min" matches the argument list
            argument types are: (<error-type>, long)

D:/Extraction/Visual_Template_Free_Form_Parsing/repo/model/csrc/cuda/ROIAlign_cuda.cu(320): error: no instance of function template "THCCeilDiv" matches the argument list
            argument types are: (int64_t, long)

D:/Extraction/Visual_Template_Free_Form_Parsing/repo/model/csrc/cuda/ROIAlign_cuda.cu(320): error: no instance of overloaded function "std::min" matches the argument list
            argument types are: (<error-type>, long)

4 errors detected in the compilation of "D:/Extraction/Visual_Template_Free_Form_Parsing/repo/model/csrc/cuda/ROIAlign_cuda.cu".
ROIAlign_cuda.cu
[2/3] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DWITH_CUDA -ID:\Extraction\Visual_Template_Free_Form_Parsing\repo\model\csrc -ID:\ProgramFiles\anaconda3\lib\site-packages\torch\include -ID:\ProgramFiles\anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -ID:\ProgramFiles\anaconda3\lib\site-packages\torch\include\TH -ID:\ProgramFiles\anaconda3\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include" -ID:\ProgramFiles\anaconda3\include -ID:\ProgramFiles\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" -c D:\Extraction\Visual_Template_Free_Form_Parsing\repo\model\csrc\cpu\ROIAlign_cpu.cpp /FoD:\Extraction\Visual_Template_Free_Form_Parsing\repo\build\temp.win-amd64-3.8\Release\Extraction\Visual_Template_Free_Form_Parsing\repo\model\csrc\cpu\ROIAlign_cpu.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
D:\ProgramFiles\anaconda3\lib\site-packages\torch\include\ATen/core/TensorBody.h(1319): warning C4522: 'at::Tensor': multiple assignment operators specified
D:\ProgramFiles\anaconda3\lib\site-packages\torch\include\ATen/core/ivalue_inl.h(389): warning C4101: 'e': unreferenced local variable
d:\programfiles\anaconda3\lib\site-packages\torch\include\pybind11\detail/common.h(106): warning C4005: 'HAVE_SNPRINTF': macro redefinition
d:\programfiles\anaconda3\include\pyerrors.h(315): note: see previous definition of 'HAVE_SNPRINTF'
D:\Extraction\Visual_Template_Free_Form_Parsing\repo\model\csrc\cpu\ROIAlign_cpu.cpp(243): warning C4996: 'at::Tensor::data': Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead.
D:\ProgramFiles\anaconda3\lib\site-packages\torch\include\ATen/core/TensorBody.h(363): note: see declaration of 'at::Tensor::data'
D:\Extraction\Visual_Template_Free_Form_Parsing\repo\model\csrc\cpu\ROIAlign_cpu.cpp(228): warning C4996: 'at::Tensor::type': Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device().
D:\ProgramFiles\anaconda3\lib\site-packages\torch\include\ATen/core/TensorBody.h(277): note: see declaration of 'at::Tensor::type'
D:\Extraction\Visual_Template_Free_Form_Parsing\repo\model\csrc\cpu\ROIAlign_cpu.cpp(229): warning C4996: 'at::Tensor::type': Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device().
D:\ProgramFiles\anaconda3\lib\site-packages\torch\include\ATen/core/TensorBody.h(277): note: see declaration of 'at::Tensor::type'
[3/3] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DWITH_CUDA -ID:\Extraction\Visual_Template_Free_Form_Parsing\repo\model\csrc -ID:\ProgramFiles\anaconda3\lib\site-packages\torch\include -ID:\ProgramFiles\anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -ID:\ProgramFiles\anaconda3\lib\site-packages\torch\include\TH -ID:\ProgramFiles\anaconda3\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include" -ID:\ProgramFiles\anaconda3\include -ID:\ProgramFiles\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" -c D:\Extraction\Visual_Template_Free_Form_Parsing\repo\model\csrc\vision.cpp /FoD:\Extraction\Visual_Template_Free_Form_Parsing\repo\build\temp.win-amd64-3.8\Release\Extraction\Visual_Template_Free_Form_Parsing\repo\model\csrc\vision.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
D:\ProgramFiles\anaconda3\lib\site-packages\torch\include\ATen/core/TensorBody.h(1319): warning C4522: 'at::Tensor': multiple assignment operators specified
D:\ProgramFiles\anaconda3\lib\site-packages\torch\include\ATen/core/ivalue_inl.h(389): warning C4101: 'e': unreferenced local variable
d:\programfiles\anaconda3\lib\site-packages\torch\include\pybind11\detail/common.h(106): warning C4005: 'HAVE_SNPRINTF': macro redefinition
d:\programfiles\anaconda3\include\pyerrors.h(315): note: see previous definition of 'HAVE_SNPRINTF'
d:\extraction\visual_template_free_form_parsing\repo\model\csrc\ROIAlign.h(18): warning C4996: 'at::Tensor::type': Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device().
D:\ProgramFiles\anaconda3\lib\site-packages\torch\include\ATen/core/TensorBody.h(277): note: see declaration of 'at::Tensor::type'
d:\extraction\visual_template_free_form_parsing\repo\model\csrc\ROIAlign.h(38): warning C4996: 'at::Tensor::type': Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device().
D:\ProgramFiles\anaconda3\lib\site-packages\torch\include\ATen/core/TensorBody.h(277): note: see declaration of 'at::Tensor::type'
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "D:\ProgramFiles\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1533, in _run_ninja_build
    subprocess.run(
  File "D:\ProgramFiles\anaconda3\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 60, in <module>
    setup(
  File "D:\ProgramFiles\anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "D:\ProgramFiles\anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\ProgramFiles\anaconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "D:\ProgramFiles\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\ProgramFiles\anaconda3\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "D:\ProgramFiles\anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\ProgramFiles\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\ProgramFiles\anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "D:\ProgramFiles\anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "D:\ProgramFiles\anaconda3\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "D:\ProgramFiles\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 670, in build_extensions
    build_ext.build_extensions(self)
  File "D:\ProgramFiles\anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "D:\ProgramFiles\anaconda3\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "D:\ProgramFiles\anaconda3\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "D:\ProgramFiles\anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "D:\ProgramFiles\anaconda3\lib\distutils\command\build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "D:\ProgramFiles\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 643, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "D:\ProgramFiles\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1250, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "D:\ProgramFiles\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1555, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

**Comment by herobd** [comment]
I don't think you need to build anymore. That was for the ROIAlign code I was using previously, but I've changed it to use the Pytorch implementation.

**Comment by PyroGenesis** [comment]
Alright, after setting up the dataset, running `python train.py -c cf_detector.json` causes the following error:
```
Traceback (most recent call last):
  File "train.py", line 129, in <module>
    main(config, args.resume)
  File "train.py", line 40, in main
    set_procname(config['name'])
  File "train.py", line 34, in set_procname
    libc = cdll.LoadLibrary('libc.so.6')    #Loading a 3rd party library C
  File "D:\ProgramFiles\anaconda3\lib\ctypes\__init__.py", line 459, in LoadLibrary
    return self._dlltype(name)
  File "D:\ProgramFiles\anaconda3\lib\ctypes\__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'libc.so.6' (or one of its dependencies). Try using the full path with constructor syntax.
```

Switching `cdll.LoadLibrary('libc.so.6')` with `cdll.msvcrt` then causes another error a couple of lines ahead:
```
Traceback (most recent call last):
  File "train.py", line 129, in <module>
    main(config, args.resume)
  File "train.py", line 40, in main
    set_procname(config['name'])
  File "train.py", line 37, in set_procname
    libc.prctl(15, byref(buff), 0, 0, 0) #Refer to "#define" of "/usr/include/linux/prctl.h" for the misterious value 16 & arg[3..5] are zero as the man page says.
  File "D:\ProgramFiles\anaconda3\lib\ctypes\__init__.py", line 394, in __getattr__
    func = self.__getitem__(name)
  File "D:\ProgramFiles\anaconda3\lib\ctypes\__init__.py", line 399, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'prctl' not found
```

Any thoughts?

**Comment by herobd** [comment]
Remove line 40 from train.py (`set_procname(config['name'])`)
This was just to rename the process name to match the config name. Totally unnecessary.

**Comment by PyroGenesis** [comment]
Now running same command leads me to this error:
```
Traceback (most recent call last):
  File "train.py", line 129, in <module>
    main(config, args.resume)
  File "train.py", line 45, in main
    data_loader, valid_data_loader = getDataLoader(config,split)
  File "D:\Extraction\Visual_Template_Free_Form_Parsing\repo\data_loader\data_loaders.py", line 95, in getDataLoader
    return withCollate(FormsBoxDetect,forms_box_detect.collate,batch_size,valid_batch_size,shuffle,shuffleValid,numDataWorkers,split,data_dir,config)
  File "D:\Extraction\Visual_Template_Free_Form_Parsing\repo\data_loader\data_loaders.py", line 130, in withCollate
    trainLoader = torch.utils.data.DataLoader(trainData, batch_size=batch_size, shuffle=shuffle, num_workers=numDataWorkers, collate_fn=collateFunc)
  File "D:\ProgramFiles\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 262, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore
  File "D:\ProgramFiles\anaconda3\lib\site-packages\torch\utils\data\sampler.py", line 103, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
```

While debugging, I found that this is due the object of `FormsBoxDetect` returning a length of 0, because it passes `config.images` (which is None) to its parent (`BoxDetectDataset`) class

Was I supposed to add `images` to the `cf_detector.json` file?

Here's my directory structure for reference
```
│
├─ Visual_Template_Free_Form_Parsing/
│  └─repo/
│      └─ ...
│  └─data/
│      └─ NAF_dataset/
│           └─ 1/
│           └─ ...
│           └─ 213/
│           └─ train_valid_test_split.json
│           └─ simple_train_valid_test_split.json
└─ Visual-Template-Free-Form-Parsing/
```

**Comment by herobd** [comment]
The data directory structure should be:
```
│  └─data/
│      └─ NAF_dataset/
│           └─ groups/
│                 └─ 1/
│                 └─ ...
│                 └─ 213/
│           └─ train_valid_test_split.json
│           └─ simple_train_valid_test_split.json
```
Did my script (`./move_images.sh`) unpack it like that?

**Comment by PyroGenesis** [comment]
No, your script was alright. I had made a mistake while converting it to a `.bat` file. Thanks for all your help!
